apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: calvine-dep
  labels:
    #Project ID
    app: ansible-gce-demo-247311
spec:
  #Run two instances of our application
  replicas: 2
  template:
    metadata:
      labels:
        app: ansible-gce-demo-247311
    spec:
      #Container details
      containers:
        - name: node-app
          image: gcr.io/ansible-gce-demo-247311/node-app:0.0.1
          imagePullPolicy: Always
          #Ports to expose
          ports:
          - containerPort: 8000
          
        
