kind: Secret
apiVersion: v1
metadata:
    # Name to reference the secret
    name: scotch-secret
type: Opaque
data:
  # Key value pairs of all your senstive records
  access_token: {ENCODED_ACCESS_TOKEN}